name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name:  Login to Docker Hub
      env:
        USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
          echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
          
    - name:  Build the Docker image with multiple tags
      id: build-docker-image
      run: |
       docker build . -f Dockerfile \
            -t ltoinel/woob:latest \
            -t ltoinel/woob:3.7
          
    - name: Push all Docker image tags
      run: |
        docker push --all-tags ltoinel/woob
